#在这里修改生成参数，例如模型路径等。
#因为有的参数训练和生成时都需要，懒得区分就把包括训练参数在内的大部分参数都放这里了（
#只有在web端生成时生效。
model:
  DDPM:
    #-----------------------------------------------#
    #   model_path指向logs文件夹下的权值文件
    #-----------------------------------------------#
    model_path: 'training/my_checkpoint/diffusion_model_last_epoch_weights.pth'
    #-----------------------------------------------#
    #   卷积通道数的设置
    #-----------------------------------------------#
    channel: 128
    #-----------------------------------------------#
    #   输入图像大小的设置
    #-----------------------------------------------#
    input_shape: [96, 96]
    #-----------------------------------------------#
    #   betas相关参数
    #-----------------------------------------------#
    schedule: "linear"
    num_timesteps: 1000
    schedule_low: 1e-4
    schedule_high: 0.02
    #-------------------------------#
    #   是否使用Cuda
    #   没有GPU可以设置成False
    #-------------------------------#
    cuda: true
    save_dir: "Web/front_end/static"

  DCGAN:
    latent_dim: 100
    model_name: "DCGAN"
    #-----------------------------------------------#
    #   模型路径
    #-----------------------------------------------#
    checkpoint_path: "training/my_checkpoint/epoch=359-step=11520.ckpt"
    image_size: 128
    batch_size: 512
    num_workers: 8
    g_lr: 0.0003
    d_lr: 0.0001
    epochs: 5000
  WGAN:
    DATALOADER:
      BATCH_SIZE: 32
      NUM_WORKERS: 0
    DATASET:
      NAME: dataset/cartoon_color
      TRAIN_TEST_RATIO: 1.0
    IMAGE:
      CHANNEL: 3
      HEIGHT: 64
      NUMBER: 10
      PIXEL_MEAN: (0.5, 0.5, 0.5)
      PIXEL_STD: (0.5, 0.5, 0.5)
      SAVE_NUMBER: 64
      SAVE_PATH: Web/front_end/static
      SAVE_ROW_NUMBER: 8
      SEPARATE: False
      WIDTH: 64
    LOG_CONFIGURATION: config/logging.conf
    MODEL:
      CHECKPOINT_DIR: checkpoints
      D:
        DIMENSION: 256
        PATH:
      DEVICE: cuda
      G:
        DIMENSION: 1024
        INPUT_SIZE: 100
        #-----------------------------------------------#
        #   模型路径
        #-----------------------------------------------#
        PATH: training\my_checkpoint\WGAN_G_epoch_39999.pth
      NAME: WGAN
      WGAN:
        CRITIC_ITERS: 5
        GENERATOR_ITERS: 40000
        IC: False
        LAMBDA: 10
        WEIGHT_CLIPING_LIMIT: 0.01
    OUTPUT_DIR: log
    PROJECT_NAME: WGAN
    SOLVER:
      BASE_LR: 0.0001
      BETAS: 0.5, 0.999
      CHECKPOINT_FREQ: 500
      EPOCHS: 300
      EVALUATE_BATCH: 128
      EVALUATE_ITERATION: 125
      WEIGHT_DECAY: 1e-05
    WALKING_LATENT_SPACE:
      IMAGE_FPS: 10
      IMAGE_NUMBER: 16
      IMAGE_ROW_NUMBER: 4
      STEP: 50
  WGAN-GP:
    #-----------------------------------------------#
    #   模型路径
    #-----------------------------------------------#
    generator_path: "training/my_checkpoint/WGANGP_gen.pth"
    discriminator_path: "training/my_checkpoint/WGANGP_disc.pth"
    channels_img: 3
    features_gen: 64
    features_disc: 64
    noise_dim: 100
    device: cuda
    max_images: 100
    final_images: 10
    seed: 42
    output_dir: "Web/front_end/static"

